VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "VBGLIShaderElement"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = True
Attribute VB_Exposed = False


Option Explicit

Public Function GetVariable() As VBGLShaderVariable
End Function
Public Function GetVariableCall(ByVal WithReturnType As Boolean) As String
End Function
Public Function GetVariableAll() As String
End Function
Public Function Element() As Variant
End Function